CREATE TABLE `einvoice_his` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `FPQQLSH` varchar(64) NOT NULL COMMENT '发票请求流水号 ',
  `FPLX` varchar(4) DEFAULT '0' COMMENT '发票类型1增值税电子普通发票;3增值税普通发票;4增值税专用发票;8成品油电子发票;9成品油普通发票(卷式);10成品油普通发票;11成品油专用发票;12增值税普通发票(卷式)',
  `ZSFS` varchar(1) DEFAULT '0' COMMENT '征税方式 0-普通征税 2-差额征税',
  `KPLX` int(1) NOT NULL COMMENT '开票类型 ',
  `FPJZ` char(1) DEFAULT '0' COMMENT '发票介质:0-电子发票;1-纸质发票。',
  `XSF_NSRSBH` char(20) DEFAULT NULL COMMENT '销售方纳税人识别号',
  `XSF_MC` varchar(100) DEFAULT NULL COMMENT '销售方名称',
  `XSF_DZDH` varchar(100) DEFAULT NULL COMMENT '销售方地址、电话',
  `XSF_YHZH` varchar(100) DEFAULT NULL COMMENT '销售方银行账号',
  `GMF_NSRSBH` char(20) DEFAULT NULL COMMENT '购买方纳税人识别号',
  `GMF_MC` varchar(100) DEFAULT NULL COMMENT '购买方名称',
  `GMF_DZDH` varchar(100) DEFAULT NULL COMMENT '购买方地址、电话',
  `GMF_YHZH` varchar(100) DEFAULT NULL COMMENT '购买方银行账号',
  `KPR` varchar(20) DEFAULT NULL COMMENT '开票人',
  `SKR` varchar(20) DEFAULT NULL COMMENT '收款人',
  `FHR` varchar(20) DEFAULT NULL COMMENT '复核人',
  `TSCHBZ` char(1) DEFAULT '0' COMMENT '特殊冲红标志',
  `YFP_DM` varchar(12) DEFAULT NULL COMMENT '原发票代码',
  `YFP_HM` varchar(8) DEFAULT NULL COMMENT '原发票号码',
  `JSHJ` decimal(15,2) DEFAULT NULL COMMENT '价税合计',
  `HJJE` decimal(15,2) DEFAULT NULL COMMENT '合计金额',
  `HJSE` decimal(15,2) DEFAULT NULL COMMENT '合计税额',
  `BZ` varchar(200) DEFAULT NULL COMMENT '备注',
  `JQBH` varchar(12) DEFAULT NULL COMMENT '税控设备编号',
  `FP_DM` varchar(12) DEFAULT NULL COMMENT '发票代码',
  `FP_HM` varchar(8) DEFAULT NULL COMMENT '发票号码',
  `KPRQ` varchar(14) DEFAULT NULL COMMENT '开票日期',
  `FP_MW` varchar(112) DEFAULT NULL COMMENT '发票密文',
  `JYM` char(20) DEFAULT NULL COMMENT '校验码',
  `EWM` varchar(3000) DEFAULT NULL COMMENT '二维码',
  `ZDRQ` date DEFAULT NULL COMMENT '制单日期',
  `SBBZ` varchar(255) DEFAULT NULL COMMENT '失败备注',
  `LYLX` char(1) DEFAULT NULL COMMENT '发票申请来源',
  `LYID` varchar(255) DEFAULT NULL COMMENT '发票申请来源id',
  `DEF1` varchar(255) DEFAULT NULL COMMENT '自定义项',
  `DEF2` varchar(255) DEFAULT NULL,
  `DEF3` varchar(255) DEFAULT NULL,
  `DEF4` varchar(255) DEFAULT NULL,
  `DEF5` varchar(255) DEFAULT NULL,
  `tenantid` varchar(64) DEFAULT NULL COMMENT '租户id',
  `creator` varchar(64) DEFAULT '~' COMMENT '创建者',
  `ts` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '时间戳',
  `status` char(1) DEFAULT NULL COMMENT '状态：1、已生成版式文件2、已下载3、已入帐',
  `bred` char(1) DEFAULT NULL COMMENT '是否被红冲',
  `corpId` varchar(64) DEFAULT NULL COMMENT '企业（集团）编码',
  `orgId` int(10) unsigned DEFAULT NULL COMMENT '组织编码',
  `BMB_BBH` varchar(20) DEFAULT '10.0',
  `SGBZ` varchar(1) DEFAULT NULL COMMENT '农产品收购标志；2=农产品收购',
  `zdybz` varchar(200) DEFAULT NULL COMMENT '自定义备注',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `zfbz` char(1) DEFAULT 'N' COMMENT '作废标志；Y=已作废，N-未作废，I=正在作废，F=作废失败（失败原因在失败备注中）',
  `account_status` char(1) DEFAULT NULL COMMENT '1-未记账；2-已记账',
  `hzxxbbh` varchar(30) DEFAULT NULL COMMENT '红字信息表编号',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `his_fpqqlsh` (`FPQQLSH`,`corpId`),
  KEY `his_hmdm` (`FP_DM`,`FP_HM`) USING BTREE,
  KEY `his_yhmydm` (`YFP_DM`,`YFP_HM`) USING BTREE,
  KEY `idx_his_corporgid` (`corpId`,`orgId`),
  KEY `idx_his_kprq` (`KPRQ`)
) ENGINE=InnoDB AUTO_INCREMENT=247 DEFAULT CHARSET=utf8;

CREATE TABLE `einvoice_his_b` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `HID` bigint(20) unsigned DEFAULT NULL COMMENT '发票申请表头id',
  `FPHXZ` int(11) DEFAULT NULL COMMENT '发票行性质',
  `XMMC` varchar(90) DEFAULT NULL COMMENT '项目名称',
  `DW` varchar(20) DEFAULT NULL COMMENT '计量单位',
  `GGXH` varchar(40) DEFAULT NULL COMMENT '规格型号',
  `XMSL` decimal(15,6) DEFAULT NULL COMMENT '项目数量',
  `XMDJ` decimal(20,10) DEFAULT NULL COMMENT '项目单价',
  `xmhsdj` decimal(20,10) DEFAULT NULL COMMENT '项目含税单价',
  `XMJE` decimal(15,2) DEFAULT NULL COMMENT '项目金额',
  `SL` decimal(6,6) DEFAULT NULL COMMENT '税率',
  `SE` decimal(15,2) DEFAULT NULL COMMENT '税额',
  `KCE` decimal(15,2) DEFAULT NULL COMMENT '扣除额',
  `HSBZ` varchar(1) DEFAULT NULL,
  `XMJSHJ` decimal(15,2) DEFAULT NULL COMMENT '项目价税合计',
  `HH` varchar(11) DEFAULT NULL COMMENT '行号',
  `ZKHHH` varchar(11) DEFAULT NULL COMMENT '折扣行行号',
  `SPBM` varchar(19) DEFAULT NULL COMMENT '商品税收分类编码 末级',
  `ZXBM` varchar(20) DEFAULT '10',
  `YHZCBS` int(1) DEFAULT '0',
  `LSLBS` char(1) DEFAULT NULL,
  `ZZSTSGL` varchar(50) DEFAULT NULL,
  `ysxmmc` varchar(90) DEFAULT NULL COMMENT '原始项目名称（不带分类）',
  `corpId` varchar(64) DEFAULT NULL,
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `ts` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '时间戳',
  PRIMARY KEY (`ID`),
  KEY `his_bid` (`HID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=369 DEFAULT CHARSET=utf8;

CREATE TABLE `einvoice_his_ext` (
  `ext_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '扩展表-主键',
  `ext_tenantid` varchar(64) DEFAULT NULL COMMENT '扩展表-租户id',
  `ext_ts` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '扩展表-时间戳',
  PRIMARY KEY (`ext_id`)
) ENGINE=InnoDB AUTO_INCREMENT=247 DEFAULT CHARSET=utf8;

CREATE TABLE `agg`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name1` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `name2` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `name3` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `name4` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `name5` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `code1` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `code2` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `code3` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `code4` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `code5` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `fpqqlsh` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `createtime` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `ts` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0),
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 4 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of agg
-- ----------------------------
INSERT INTO `agg` VALUES (1, 'cn', 'en', 'fr', 'jp', 'kr', 'cn_code', 'en_code', 'fr_code', 'jp_code', 'kr_code', '1760P', '2020-04-16 18:54:24', '2020-04-16 19:52:35');
INSERT INTO `agg` VALUES (2, 'cn', 'en', 'fr', 'jp', 'kr', 'cn_code', 'en_code', 'fr_code', 'jp_code', 'kr_code', '1760P', '2020-04-16 18:54:24', '2020-04-16 19:52:47');
INSERT INTO `agg` VALUES (3, 'cn', 'en', 'fr', 'jp', 'kr', 'cn_code', 'en_code', 'fr_code', 'jp_code', 'kr_code', '1760P', '2020-04-16 18:54:24', '2020-04-16 19:52:48');
